#! /bin/bash
if [ ! -z "$1" ];then
    TAGS="$1"
else
    TAGS=""
fi
function update_file() {
    if [ ! -z "$1" ] && [ ! -z "$2" ] && [ ! -z "$3" ];then
        GetValue="$(cat "$3" | grep "$1")"
        GetPath=${3/"./"/"/"}
        [ "$GetValue" != "$2" ] && \
        sed -i "s/$1.*/$2/g" "$3"
        [ ! -z "$(git status | grep "modified" )" ] && \
        git add "$3" && \
        git commit -m "update builder $2"
    fi
}
function update_fileB() {
    if [ ! -z "$1" ] && [ ! -z "$2" ] && [ ! -z "$3" ];then
        GetValue="$(cat "$3" | grep "$1")"
        GetPath=${3/"./"/"/"}
        [ "$GetValue" != "$2" ] && \
        sed -i "s/$1.*/$2"'"'"/g" "$3"
        [ ! -z "$(git status | grep "modified" )" ] && \
        git add "$3" && \
        git commit -m "update builder $2"
    fi
}
function make_changes() {
    git checkout master && git checkout -b $1-$2
    git checkout $1-$2 && update_fileB "00000" "$2" "./$1.sh" && update_file 'do-main.sh' "$1.sh" './.circleci/config.yml'
}

ListBranch=""
for Files in do-main
do
    if [ "$TAGS" == "all" ];then
        if [[ -e ${Files}.sh ]];then
            for Types in proton dtc gcc gcc12 storm strix sdclang atom zyc neutron
            do
                git branch -D $Files-$Types
                make_changes $Files $Types
                ListBranch="$ListBranch $Files-$Types"
                git checkout master
            done 
        fi
    else
        if [[ -e ${Files}.sh ]];then
            if [ "$TAGS" == "gcc" ] || [ "$TAGS" == "gcc12" ] || [ "$TAGS" == "proton" ] || [ "$TAGS" == "dtc" ] || [ "$TAGS" == "storm" ] || [ "$TAGS" == "strix" ] || [ "$TAGS" == "sdclang" ] || [ "$TAGS" == "atom" ] || [ "$TAGS" == "zyc" ] || [ "$TAGS" == "neutron" ];then
                git branch -D $Files-$TAGS
                make_changes $Files $TAGS
                ListBranch="$ListBranch $Files-$TAGS"
                git checkout master
            fi
        fi
    fi
done

if [ "$2" == "drone" ];then
git push -f rmt2 $ListBranch
else
git push -f origin $ListBranch
fi
